export const NAV_LINKS = ["Home", "Shop Pets", "Services", "About", "Contact"];

// Tab → which category names are shown
export const TAB_FILTER = {
  "All pets":   ["Dogs", "Cats", "Birds", "Rabbit", "Fishes", "Reptiles"],
  "Puppies":    ["Dogs"],
  "Kittens":    ["Cats"],
  "Rabbit": ["Rabbit", "Birds", "Fishes", "Reptiles"],
};

export const CATEGORIES = [
  {
    name: "Dogs", 
    count: 48, 
    ProfileImage: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg", 
    bg: "bg-amber-50",
    accent: "from-amber-400 to-orange-300",
    description: "Loyal, playful companions for every home and lifestyle.",
    pets: [
      { name: "Buddy", 
        breed: "Golden Retriever", 
        sex: "Male", 
        age: "2 months", 
        price: 850, 
        tags: ["Vaccinated", "Microchipped"], 
        badge: "New arrival", 
        images: "https://images.pexels.com/photos/32378666/pexels-photo-32378666.jpeg", 
        liked: false 
      },
      { name: "Max", 
        breed: "Labrador", 
        sex: "Male", 
        age: "3 months", 
        price: 780, 
        tags: ["Kid Friendly", "Trained"], 
        badge: null, 
        images: "https://images.pexels.com/photos/8176935/pexels-photo-8176935.jpeg", 
        liked: false 
      },
      { name: "Coco", 
        breed: "Poodle", 
        sex: "Female", 
        age: "4 months", 
        price: 920, 
        tags: ["Hypoallergenic"], 
        badge: "Popular", images: "https://images.pexels.com/photos/1790445/pexels-photo-1790445.jpeg", 
        liked: true  
      },
      { name: "Rocky", 
        breed: "German Shepherd", 
        sex: "Male", 
        age: "6 months", 
        price: 1100, 
        tags: ["Trained", "Vaccinated"], 
        badge: null, 
        images: "https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg", 
        liked: false 
      },
    ],
  },
  {
    name: "Cats", 
    count: 35, 
    ProfileImage: "https://images.pexels.com/photos/32817654/pexels-photo-32817654.jpeg", 
    bg: "bg-rose-50",
    accent: "from-rose-400 to-pink-300",
    description: "Independent, affectionate felines for cosy companionship.",
    pets: [ 
      { 
        name: "Luna el cat ", 
        breed: "Siamese", 
        sex: "Female", 
        age: "3 months", 
        price: 600,  
        tags: ["Kid Friendly"],  
        badge: "Last 3 left", 
        images: "https://images.pexels.com/photos/12115374/pexels-photo-12115374.jpeg", 
        liked: true  
      },
      { 
        name: "Mochi Mautot hi papa", 
        breed: "Scottish Fold", 
        sex: "Female", 
        age: "2 months", 
        price: 850, 
        tags: ["Indoor", "Gentle"], 
        badge: "New arrival", 
        images: "https://images.pexels.com/photos/29461967/pexels-photo-29461967.jpeg", 
        liked: false 
      },
      { 
        name: "Oliver Mautot",  
        breed: "Maine Coon",  
        sex: "Male", 
        age: "5 months", 
        price: 750,  
        tags: ["Fluffy", "Friendly"], 
        badge: null, 
        images: "https://images.pexels.com/photos/15815711/pexels-photo-15815711.jpeg", 
        liked: false 
      },
      { 
        name: "Bella", 
        breed: "Ragdoll", 
        sex: "Female", 
        age: "3 months", 
        price: 680, 
        tags: ["Kid Friendly", "Gentle"], 
        badge: null, 
        images: "https://images.pexels.com/photos/7627100/pexels-photo-7627100.jpeg", 
        liked: true 
      },
    ],
  },
  {
    name: "Birds", 
    count: 18, 
    ProfileImage: "https://images.pexels.com/photos/1059823/pexels-photo-1059823.jpeg", 
    bg: "bg-sky-50",
    accent: "from-sky-400 to-cyan-300",
    description: "Vibrant, intelligent birds that light up any room.",
    pets: [
      { name: "Rio", 
        breed: "Macaw", 
        sex: "Male", 
        age: "1 year", 
        price: 1200, 
        tags: ["Talkative", "Trained"], 
        badge: null,
        images: "https://images.pexels.com/photos/17819986/pexels-photo-17819986.jpeg", 
        liked: false 
      },
      { 
        name: "Sky", 
        breed: "Parakeet", 
        sex: "Female", 
        age: "6 months", 
        price: 180,  
        tags: ["Starter pet", "Friendly"], 
        badge: "Popular", 
        badgeColor: "bg-blue-500", 
        images: "https://images.pexels.com/photos/9214628/pexels-photo-9214628.jpeg", 
        bg: "from-sky-100 to-blue-50", 
        liked: false 
      },
      { name: "Pepper", 
        breed: "Cockatiel", 
        sex: "Male", 
        age: "8 months", 
        price: 320, 
        tags: ["Gentle", "Whistler"], 
        badge: null, 
        images: "https://images.pexels.com/photos/2569222/pexels-photo-2569222.jpeg",
        liked: true 
      },
      {
        name: "Cleo", 
        breed: "African Grey", 
        sex: "Female", 
        age: "2 years", 
        price: 2200, 
        tags: ["Very Talkative", "Trained"], 
        badge: "Rare", 
        images: "https://images.pexels.com/photos/18138626/pexels-photo-18138626.jpeg", 
        liked: false
      },
    ],
  },
  {
    name: "Rabbit", 
    count: 22, 
    ProfileImage: "https://images.pexels.com/photos/3828097/pexels-photo-3828097.jpeg", 
    bg: "bg-cyan-50",
    accent: "from-violet-400 to-purple-300",
    description: "Tiny friends with huge personalities, perfect for smaller spaces.",
    pets: [
      { name: "Daisy", 
        breed: "Holland Lop", 
        sex: "Female", 
        age: "2 months", 
        price: 150, 
        tags: ["Small pet", "Gentle"], 
        badge: null, 
        images: "https://images.pexels.com/photos/6356163/pexels-photo-6356163.jpeg", 
        liked: false 
      },
      { 
        name: "Nibbles", 
        breed: "Hamster", 
        sex: "Male", 
        age: "3 months", 
        price: 45, 
        tags: ["Starter pet", "Low care"], 
        badge: "Popular", 
        badgeColor: "bg-blue-500", 
        images: "https://images.pexels.com/photos/372166/pexels-photo-372166.jpeg", 
        bg: "from-violet-100 to-purple-50", 
        liked: false 
      },
      { 
        name: "Peanut", 
        breed: "Guinea Pig", 
        sex: "Female", 
        age: "4 months", 
        price: 80, 
        tags: ["Friendly", "Kid Safe"],
         badge: null, 
         images: "https://images.pexels.com/photos/27289768/pexels-photo-27289768.jpeg", 
         liked: true  
      },
      {
        name: "Pip", 
        breed: "Chinchilla", 
        sex: "Male",  
        age: "6 months", 
        price: 220,  
        tags: ["Soft", "Exotic"], 
        badge: "New arrival", 
        images: "https://images.pexels.com/photos/583676/pexels-photo-583676.jpeg", 
        liked: false 
      },
    ],
  },
  {
    name: "Fishes", 
    count: 40, 
    ProfileImage: "https://images.pexels.com/photos/29704986/pexels-photo-29704986.jpeg", 
    bg: "bg-cyan-50",
    accent: "from-cyan-400 to-teal-300",
    description: "Peaceful aquatic life to bring calm and colour to your home.",
    pets: [
      { 
        name: "Nemo", 
        breed: "Clownfish", 
        sex: "Male", 
        age: "1 year", 
        price: 40, 
        tags: ["Saltwater", "Vibrant"], 
        badge: "Popular", 
        images: "https://images.pexels.com/photos/29704985/pexels-photo-29704985.jpeg", 
        liked: false 
      },
      { 
        name: "Blue", 
        breed: "Betta",  
        sex: "Male", 
        age: "8 months", 
        price: 25, 
        tags: ["Easy care", "Colourful"], 
        badge: null, 
        badgeColor: "", 
        images: "https://images.pexels.com/photos/8807482/pexels-photo-8807482.jpeg", 
        bg: "from-blue-100 to-cyan-50", 
        liked: true  
      },
      { 
        name: "Goldie", 
        breed: "Goldfish", 
        sex: "Female", 
        age: "6 months", 
        price: 15, 
        tags: ["Starter", "Freshwater"], 
        badge: null, 
        badgeColor: "", 
        images: "https://images.pexels.com/photos/8807482/pexels-photo-8807482.jpeg", 
        bg: "from-yellow-100 to-cyan-50", 
        liked: false 
      },
      { 
        name: "Dory",
        breed: "Blue Tang", 
        sex: "Female", 
        age: "1 year", 
        price: 90, 
        tags: ["Saltwater", "Friendly"], 
        badge: "Rare", 
        badgeColor: "bg-violet-500", 
        images: "https://images.pexels.com/photos/4593104/pexels-photo-4593104.jpeg", 
        bg: "from-cyan-100 to-teal-50", 
        liked: false 
      },
    ],
  },
  {
    name: "Reptiles", 
    count: 12, 
    ProfileImage: "https://images.pexels.com/photos/584165/pexels-photo-584165.jpeg", 
    bg: "bg-emerald-50",
    accent: "from-emerald-400 to-green-300",
    description: "Unique, fascinating reptiles for adventurous pet lovers.",
    pets: [
      { 
        name: "Rex", 
        breed: "Bearded Dragon", 
        sex: "Male", 
        age: "6 months", 
        price: 350,  
        tags: ["Beginner Friendly", "Calm"],  
        badge: "Popular", 
        badgeColor: "bg-blue-500", 
        images: "https://images.pexels.com/photos/20546357/pexels-photo-20546357.jpeg",   
        bg: "from-amber-100 to-emerald-50", 
        liked: false 
      },
      { 
        name: "Slinky", 
        breed: "Corn Snake", 
        sex: "Female", 
        age: "1 year", 
        price: 180, 
        tags: ["Non-venomous", "Gentle"], 
        badge: null, 
        badgeColor: "", 
        images: "https://images.pexels.com/photos/34426/snake-rainbow-boa-reptile-scale.jpg", 
        bg: "from-emerald-100 to-green-50", 
        liked: false 
      },
      { 
        name: "Shelly", 
        breed: "Red-eared Turtle", 
        sex: "Female", 
        age: "2 years",  
        price: 120, 
        tags: ["Low care", "Long life"], 
        badge: null, 
        badgeColor: "", 
        images: "https://images.pexels.com/photos/4017819/pexels-photo-4017819.jpeg",  
        bg: "from-teal-100 to-emerald-50", 
        liked: true  
      },
      { 
        name: "Gex", 
        breed: "Leopard Gecko", 
        sex: "Male",  
        age: "8 months", 
        price: 200, 
        tags: ["Beginner", "Nocturnal"], 
        badge: "New arrival",  
        badgeColor: "bg-emerald-500", 
        images: "https://images.pexels.com/photos/28010600/pexels-photo-28010600.jpeg",   
        bg: "from-lime-100 to-emerald-50",  
        liked: false },
    ],
  },
];

export const PETS = CATEGORIES.flatMap((c) => c.pets);

export const SERVICES = [
  { icon: "✂️", title: "Pet grooming",      desc: "Baths, haircuts, nail trimming & more. Keep your pet fresh and comfortable with professional grooming tailored to their breed and coat type.", cta: "Book grooming",   meta: "270+ available slots"     },
  { icon: "🩺", title: "Veterinary care",   desc: "Regular health checkups, vaccinations, and emergency care — all under one roof for your peace of mind.",                                       cta: "Consult a vet",   meta: "Health guarantee included" },
  { icon: "🎓", title: "Training & behavior",desc: "Personalised training programs to help your pet learn good manners and build a strong bond with you.",                                         cta: "Explore classes", meta: "Group & 1:1 sessions"      },
];

export const WHY_FEATURES = [
  { icon: "🛡️", title: "Health guarantee",    desc: "Each pet passes a complete health check with vaccinations up to date and clear medical history."              },
  { icon: "🌟", title: "Lifetime guidance",    desc: "Our experts support you with nutrition, training, and care tips at every stage of your pet's life."           },
  { icon: "🏪", title: "One-stop shop",        desc: "Adoption, supplies, grooming, training, and vet care — all in one convenient destination."                    },
  { icon: "💚", title: "Ethical & responsible",desc: "We partner only with ethical breeders and rescues, prioritising animal welfare above all."                    },
];

export const FOOTER_LINKS = {
  Explore: ["Home", "Shop pets", "Pet supplies", "Gift cards"],
  Support: ["About us", "Health guarantee", "FAQ", "Privacy & terms"],
};